apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
spec:
  replicas: 3 # Number of pods
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
        - name: nextjs-container
          image: nextjs-app:local
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"