name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if your main branch is named differently

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Ensure Node.js 18 or higher

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Check if 'origin' remote exists, and add it if not
          git remote get-url origin || git remote add origin https://github.com/${{ github.repository }}.git
          
          # Initialize and switch to gh-pages branch
          git fetch origin
          git checkout -B gh-pages

          # Copy the generated files from the output directory
          cp -r out/* .

          # Commit and push changes to gh-pages branch
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages